### ISSUE TITLE
[question] How does it compares with RxFire?

### ISSUE THREAD

**Issue by fredguth** [jacobbowdoin/sveltefirets#6]
I understand this code let you access Firestore collections as stores (observables), right?  Isn't that what RxFire does? 
Am I missing something here? 

Also, I don't get the `OnLine` methods.  What are they for?  I thought Firestore handled the offline case transparently for the developer.

**Comment by jacob-8** [comment]
> I understand this code let you access Firestore collections as stores (observables), right? Isn't that what RxFire does?
Am I missing something here?

Similar to the source inspiration, [Sveltefire](https://github.com/codediodeio/sveltefire), this allows you to use Firebase declaratively via Svelte components but adds a few key items among other things:

- Typescript intellisense (e.g. component props and data emitted/passed down)
- SvelteKit/SSR friendly
- Easy integration w/ FirebaseUI for Web auth - that still hasn't updated to Firebase 9
- database helpers that save user ids and timestamps

RxFire is great and could easily be used in tandem with this library. However, I've found that with Svelte custom stores being so easy to build, one custom store for documents and one for collections is all I've ever needed, thus making RxFire obsolete for my purposes. As well, RxFire obviously does not provide Svelte components for easy page composition.

> Also, I don't get the `OnLine` methods. What are they for? I thought Firestore handled the offline case transparently for the developer.

I'll copy from https://sveltefirets.vercel.app/8-offline-persistence: 

> By design Firebase’ `addDoc`, `setDoc`, `updateDoc`, and `deleteDoc` methods (and by extension this library’s `add`, `set`, `update`, and `deleteDocument` helper methods) return promises that resolve only once changes are written to the server and NOT the cache. If poor internet or no internet exists, these promises won’t resolve. So in a use case where a user with weak internet creates a new item and you write your code to await the addition of the item to the database before navigating to a page where that item can be edited further, nothing will happen and users will be left wondering what is broken with the site. You won’t discover this in development because you have great internet! But it could plague you if you are unaware. This is why I’ve set up this library to also include the equivalent Firestore Lite helpers methods as seen in https://github.com/jacobbowdoin/sveltefirets/blob/main/packages/sveltefirets/src/lib/client/firestore-lite.ts - addOnline, setOnline, updateOnline, and deleteOnline.

Firebase is built this way by design - see the links in https://sveltefirets.vercel.app/8-offline-persistence for more discussion about this and different ways to handle it based on your needs.

**Comment by fredguth** [comment]
So addOnline, setOnline, etc will work offline and update the server when the network is back?  If so, shouldn't it be called addOffline, setOffline, etc?

**Comment by jacob-8** [comment]
> So addOnline, setOnline, etc will work offline and update the server when the network is back? If so, shouldn't it be called addOffline, setOffline, etc?

Firebase by default works online or offline, so the default `add`, `set`, etc work anytime because of Firestore's cache. The reason for `addOnline` is sometimes you only want to add a document when the user is truly connected to the server. In one of my use cases, users are allowed to create a new dictionary for their language (they will only ever do this once) and we don't want them creating a dictionary just on their local cache, thinking they actually created one in our system. Neither Firebase' cache nor user internet connections are flawless so certain things of great importance we don't want left to chance that they actually make it to the server. In theory, Firebase will eventually get the data to the server, but in reality this doesn't happen every time. Just like any other database solution, there are certain times you want to make sure data made it to the server before moving users to the next step. In these cases, you should use `addOnline`.

This is behavior inherent to all users of Firebase, regardless of platform, many users just don't know all the finer nuances of a caching database that's not perfect. In actual usage, we've run into enough issues to know these sorts of saving methods are important to have available.

**Comment by fredguth** [comment]
Thanks for the explanation and for all your patience with me. I am new to Firestore, I am more used to CouchDB/PouchDB.
 
I am a Fireship Pro subscriber and I watched the aforementioned video, but I must confess that not being used to Angular it was a little difficult to get the point. I found the demo in this repo much more insightful (btw, the api route is broken, I guess it was due a sveltekit update).  
 
One thing that might help in the documentation is to have `with sveltefirets/without sveltefirets` examples. Maybe the ubiquitous `todomvc` example or other small application idea.
